### ISSUE TITLE
Any plan about performance improving?

### ISSUE THREAD

**Issue by forsakenyang** [Unity-Technologies/AssetGraph#20]
There are about 20k files (over 3GB size) in my project.It takes very long time to operate AssetGraph nodes.Such as creating node, modifing name,grouping and filtering assets.It is about 10 seconds costing at first time I create the loader node, but the performace runs to worse quickly when more nodes created.It seems that AssetGraph recalculate the whole nodes even if just only changing the node name.

Or,is it possible to provide an option to refresh nodes by manual to avoid this issue?

**Comment by hiroki-o** [comment]
Thank you for reporting this. I will make the improvement to the performance.

**Comment by hiroki-o** [comment]
I am working on this now, looking forward to solve this by release/1.1

**Comment by hiroki-o** [comment]
Fixed this with 1.1/release. Now you should be able to work in productive speed with project which holds tens of thousands of assets.
