### ISSUE TITLE
PrefabBuilder and incremental asset bundle building

### ISSUE THREAD

**Issue by nistake** [Unity-Technologies/AssetGraph#23]
PrefabBuilder always generates a new prefab regardless of whether dependent assets are updated or not. So incremental asset bundle building of Unity5 does not work. Is it possible to add a function that PrefabBuilder generates a new prefab only if sources are changed ?

**Comment by hiroki-o** [comment]
Fixed in 1.1/release. PrefabBuilder now checks source asset changes as well as configuration changes in PrefabBuilder to avoid unnecessary rebuilding.
