### ISSUE TITLE
Question: How you solved layout. e.g lines not to be drawn over nodes and go arround them

### ISSUE THREAD

**Issue by winxalex** [Unity-Technologies/AssetGraph#26]
If you aware of such algorithm let me know?

**Comment by hiroki-o** [comment]
AssetGraph is not equipped with such algorithms and currently doesn't have plan to implement auto layout.

But if you want to do it yourself, it looks a good idea to start from Wikipedia
https://en.wikipedia.org/wiki/Force-directed_graph_drawing

Also, there are some good software that implement variety of graph layout such as GraphViz. This also may be a good place to start.
http://www.graphviz.org/gallery/
